### ISSUE TITLE
babelnet-clusters

### ISSUE THREAD

**Issue by alexanderpanchenko** [uhh-lt/mangosteen#4]
after doing ``make clean`` and then ``make all`` i get this: do we use any api calls actually, not a db dump? is there any way to indicate a path to a BN dump? 

INFO: Extracting 192
May 02, 2018 9:39:13 PM de.tudarmstadt.lt.babelnet.extract.actions.SynsetsAction lambda$null$4
INFO: Extracting 1152
May 02, 2018 9:39:13 PM de.tudarmstadt.lt.babelnet.extract.actions.SynsetsAction lambda$null$4
INFO: Extracting 2208
May 02, 2018 9:39:13 PM de.tudarmstadt.lt.babelnet.extract.actions.SynsetsAction lambda$null$4
INFO: Extracting 1472
May 02, 2018 9:39:13 PM de.tudarmstadt.lt.babelnet.extract.actions.SynsetsAction lambda$null$4
INFO: Extracting 1024
May 02, 2018 9:39:13 PM de.tudarmstadt.lt.babelnet.extract.actions.SynsetsAction lambda$null$4
INFO: Extracting 128
May 02, 2018 9:39:13 PM de.tudarmstadt.lt.babelnet.extract.actions.SynsetsAction lambda$null$4
INFO: Extracting 1664
May 02, 2018 9:39:13 PM de.tudarmstadt.lt.babelnet.extract.actions.SynsetsAction lambda$null$4
INFO: Extracting 1568
May 02, 2018 9:39:13 PM de.tudarmstadt.lt.babelnet.extract.actions.SynsetsAction lambda$null$4
INFO: Extracting 288
May 02, 2018 9:39:13 PM de.tudarmstadt.lt.babelnet.extract.actions.SynsetsAction lambda$null$4
INFO: Extracting 1824
May 02, 2018 9:39:13 PM de.tudarmstadt.lt.babelnet.extract.actions.SynsetsAction lambda$null$4
INFO: Extracting 2080
Exception in thread "main" java.lang.RuntimeException: Your key is not valid or the daily requests limit has been reached. Please visit http://babelnet.org.
        at it.uniroma1.lcl.babelnet.BabelNetFullOnline.getSynsets(BabelNetFullOnline.java:136)
        at it.uniroma1.lcl.babelnet.BabelNet.getSynsets(BabelNet.java:891)
        at it.uniroma1.lcl.babelnet.BabelNet.getSynsets(BabelNet.java:799)
        at it.uniroma1.lcl.babelnet.BabelNet.getSynsets(BabelNet.java:611)
        at it.uniroma1.lcl.babelnet.BabelNet.getSynsets(BabelNet.java:571)
        at de.tudarmstadt.lt.babelnet.extract.actions.SynsetsAction.lambda$null$4(SynsetsAction.java:72)
        at de.tudarmstadt.lt.babelnet.extract.actions.SynsetsAction$$Lambda$8/194494468.accept(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1612)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:902)
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1689)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1644)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Makefile:58: recipe for target 'babelnet-clusters' failed
make: *** [babelnet-clusters] Error 1

**Comment by dustalov** [comment]
This operation expects that the offline BabelNet database is installed and properly configured. This is a bit painful process that I did not automate.

**Comment by alexanderpanchenko** [comment]
ok, but maybe you can provide some instructions in the readme as a
prequesties? where is the dump currently on ltcpu3?

**Comment by dustalov** [comment]
You stole my thoughts. Fixed in https://github.com/uhh-lt/mangosteen/commit/38cc1f642cef8f105ede730177b26b4a72f08942. The second answer is yes.

**Comment by alexanderpanchenko** [comment]
thanks: i found this file:

/home/dmitry$ du -sh BabelNet-3.7/
25G BabelNet-3.7/

is this the dump? how to 'install' it so that the error does not appear
anymore (copy to the 'code' directory? indicate path somewhere?)

**Comment by dustalov** [comment]
The name of the original file is `babelnet-3.7-index-bundle.tar.bz2`. The mentioned directory contains the configured distribution of BabelNet. As far as I remember, the BabelNet API in `babelnet-extract` should be pointed to the valid BabelNet index directory and the WordNet database files.

On that machine, have a look at `~dmitry/babelnet-extract/config`.
